[2025-07-18 03:39:45,267][src.utils.utils][INFO] - [rank: 0] Enforcing tags! <cfg.extras.enforce_tags=True>
[2025-07-18 03:39:45,272][src.utils.utils][INFO] - [rank: 0] Printing config tree with Rich! <cfg.extras.print_config=True>
[2025-07-18 03:39:45,316][__main__][INFO] - [rank: 0] Instantiating datamodule <src.data.sevir_datamodule.SEVIRDataModule>
[2025-07-18 03:39:45,448][__main__][INFO] - [rank: 0] Instantiating model <src.models.convlstm_module.VILNowcastingModel>
[2025-07-18 03:39:45,458][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmpn1254gag
[2025-07-18 03:39:45,458][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmpn1254gag/_remote_module_non_scriptable.py
[2025-07-18 03:39:45,524][__main__][INFO] - [rank: 0] Instantiating callbacks...
[2025-07-18 03:39:45,524][src.utils.instantiators][INFO] - [rank: 0] Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2025-07-18 03:39:45,529][src.utils.instantiators][INFO] - [rank: 0] Instantiating callback <lightning.pytorch.callbacks.EarlyStopping>
[2025-07-18 03:39:45,530][src.utils.instantiators][INFO] - [rank: 0] Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2025-07-18 03:39:45,530][src.utils.instantiators][INFO] - [rank: 0] Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2025-07-18 03:39:45,530][__main__][INFO] - [rank: 0] Instantiating loggers...
[2025-07-18 03:39:45,531][src.utils.instantiators][INFO] - [rank: 0] Instantiating logger <lightning.pytorch.loggers.wandb.WandbLogger>
[2025-07-18 03:39:45,533][src.utils.utils][ERROR] - [rank: 0] 
Traceback (most recent call last):
  File "/data0/cjl/.local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/data0/cjl/.local/lib/python3.8/site-packages/lightning/pytorch/loggers/wandb.py", line 309, in __init__
    raise ModuleNotFoundError(str(_WANDB_AVAILABLE))
ModuleNotFoundError: Requirement 'wandb>=0.12.10' not met. HINT: Try running `pip install -U 'wandb>=0.12.10'`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data0/cjl/code/nowcasting/2025_0712sevir测试/lightning-hydra-template/src/utils/utils.py", line 68, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 67, in train
    logger: List[Logger] = instantiate_loggers(cfg.get("logger"))
  File "/data0/cjl/code/nowcasting/2025_0712sevir测试/lightning-hydra-template/src/utils/instantiators.py", line 54, in instantiate_loggers
    logger.append(hydra.utils.instantiate(lg_conf))
  File "/data0/cjl/.local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/data0/cjl/.local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/data0/cjl/.local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'lightning.pytorch.loggers.wandb.WandbLogger':
ModuleNotFoundError("Requirement 'wandb>=0.12.10' not met. HINT: Try running `pip install -U 'wandb>=0.12.10'`")
full_key: logger.wandb
[2025-07-18 03:39:45,534][src.utils.utils][INFO] - [rank: 0] Output dir: /data0/cjl/code/nowcasting/2025_0712sevir测试/lightning-hydra-template/logs/train/runs/2025-07-18_03-39-45
